version: '3.8'

services:
  pontomenos:
    container_name: pontomenos
    image: node:24
    restart: unless-stopped
    working_dir: /pontomenos
    volumes:
      - /volume1/docker/pontomenos:/pontomenos:rw
    environment:
      - TZ=America/Sao_Paulo
      - NODE_ENV=production
      - PORT=9993
    ports:
      - "9993:9993"
    command:
      - bash
      - -c
      - |
        npm install &&
        node server.js
